from django.urls import path,include
from api import views


urlpatterns=[
         path('consumers/',views.consumers,name='consumers'),
         path('consumers_bulk/',views.consumers_bulk,name='consumers'),
        #  path('consumers_test_new/',views.consumers_test_new,name='consumers'),
        #  path('consumers_6_2_18/',views.consumers_6_2_18,name='consumers_6_2_18'),
         path('register/',views.meterReaderRegistrationfun,name='consumers'),
         path('registerupdate/',views.meterReaderRegistrationUpdateOffice,name='consumers'),
         path('login/',views.metereReaderlogin,name='consumers'),
         path('getconsumers/',views.getconsumers,name='getconsumers'),
         path('mvcards/',views.mvcards,name='getconsumers'), 
         path('getregdata/',views.getregdata,name='getconsumers'),
         path('deleteconsumers/',views.deleteconsumers,name='deleteconsumers'),
         
         
    
#      path('jsondata/',views.get_jsonData,name='userdata'),
    path('officejson/',views.get_officedata,name='userdata'),
    path('loginuser/',views.loginuser,name='loginuser'),
    path('discom/',views.get_discom,name='userdata'),
    path('zone/',views.get_zone,name='userdata'),
    path('circle/',views.get_circle,name='userdata'),
    path('division/',views.get_division,name='userdata'),
    path('subdivision/',views.get_subdivision,name='userdata'),
    path('section/',views.get_section,name='userdata'),
    path('sectionuser/',views.get_sectionforuser,name='userdata'),
    path('metersummary/',views.get_meter_summary,name='userdata'),
    path('agencywisesummary/',views.agencywisesummary,name='userdata'),
    path('meterreaderdetail/',views.get_meter_reader_detail,name='userdata'),
    path('ocrsummary/',views.ocrsummary,name='userdata'),
    path('locationdiscom/',views.locationdiscom,name='userdata'),
    path('locationzone/',views.locationzone,name='userdata'),
    path('locationcircle/',views.locationcircle,name='userdata'),
    path('locationdivision/',views.locationdivision,name='userdata'),
    path('locationsubdivision/',views.locationsubdivision,name='userdata'),
    path('locationwisediscom/',views.locationwisediscom,name='userdata'),
    path('locationwisezone/',views.locationwisezone,name='userdata'),
    path('locationwisecircle/',views.locationwisecircle,name='userdata'),
    path('locationwisedivision/',views.locationwisedivision,name='userdata'),
    path('locationwisesubdivision/',views.locationwisesubdivision,name='userdata'),
    path('exceptionlist/',views.exceptionlist,name='userdata'),
    path('minidashboard/',views.minidashboard,name='userdata'),
    path('consumerwisedetail/',views.consumer_wise_details,name='consumerwisedetail'),
    path('getconsumerscount/',views.getconsumerscount,name='userdata'),
    path('totalcounts/',views.totalcounts,name='userdata'),
#     path('getAllMridfenc/',views.getAllMridfenc,name='getAllMridfenc'),
    path('getmridforsection/',views.getmridforSection,name='getmridforSection'),
    path('test/',views.test,name='getmridforSection'),
    # path('topmeterreaders/',views.topmeterreaders,name='getmridforSection'),
    path('topmeterreaders1/',views.topmeterreaders1,name='getmridforSection'),
    path('mrwisedailydata/',views.mrwisedailydata,name='getmridforSection'),
    path('consdetails/',views.consdetail,name='getmridforSection'),
    path('qccheck/',views.qccheck,name='qccheck'),
    path('qccheckupdate/',views.qccheckupdate,name='qccheckupdate'),
    path('mvcheck/',views.mvcheck,name='qccheckupdate'),
    path('monthwiseexceptiondashboard/',views.monthwiseexceptiondashboard,name='monthwiseexceptiondashboard'),
    path('monthwiseexceptiondashboardnbpdcl/',views.monthwiseexceptiondashboardnbpdcl,name='monthwiseexceptiondashboardnbpdcl'),
    path('monthwiseexceptiondashboardsbpdcl/',views.monthwiseexceptiondashboardsbpdcl,name='monthwiseexceptiondashboardsbpdcl'),
    
    path('minidashboardmonth/',views.minidashboardmonth,name='qccheckupdate'),
    # path('exceptionlistmonth/',views.exceptionlistmonth,name='qccheckupdate'),
    path('consumerstest/',views.consumerstest,name='qccheckupdate'),
    path('consumerstest/',views.consumerstest,name='qccheckupdate'),
    path('clusters/',views.clusters,name='PersonView'),
    path('monthdata/',views.monthdata,name='PersonView'),
    path('dailydata/',views.dailydata,name='PersonView'),
    path('geocluster/',views.geocluster,name='PersonView'),
    path('tester/',views.tester,name='PersonView'),
    path('minidashboardsbpdclmonth/',views.minidashboardsbpdclmonth,name='PersonView'),
    path('minidashboardnbpdclmonth/',views.minidashboardnbpdclmonth,name='PersonView'),
    path('exceptionlistsbpdclmonth/',views.exceptionlistsbpdclmonth,name='PersonView'),
    path('topmeterreaderssbpdcl/',views.topmeterreaderssbpdcl,name='PersonView'),
    path('topmeterreadersnbpdcl/',views.topmeterreadersnbpdcl,name='PersonView'),
    path('exceptionlistnbpdclmonth/',views.exceptionlistnbpdclmonth,name='PersonView'),
    path('clusterstest/',views.clusterstest,name='PersonView'),
    path('clusterstestnew/',views.clusterstestnew,name='PersonView'),
    path('get_meter_summarytest/',views.get_meter_summarytest,name='PersonView'),
    path('consumerwisemap/',views.consumerwisemap,name='PersonView'),
    path('geoclusternew/',views.geoclusternew,name='geoclusternew'),
    path('dailybilling/',views.dailybilling,name='PersonView'),
    path('mvchecktest/',views.mvchecktest,name='PersonView'),
    path('dashboarddailydata/',views.dashboarddailydata,name='PersonView'),
    path('dashboarddailydatanbpdcl/',views.dashboarddailydatanbpdcl,name='PersonView'),
    path('dashboarddailydatasbpdcl/',views.dashboarddailydatasbpdcl,name='PersonView'),
    path('performancewisemrs/',views.performancewisemrs,name='PersonView'),
    path('performancewisemrssbpdcl/',views.performancewisemrssbpdcl,name='PersonView'),
    path('performancewisemrsnbpdcl/',views.performancewisemrsnbpdcl,name='PersonView'),
    path('getofficedatalist/',views.getofficedatalist,name='PersonView'),
    path('mvsummarycards/',views.mvsummarycards,name='PersonView'),
    path('dashboardagencywise/',views.dashboardagencywise,name='dashboardagencywise'),
    path('dashboardagencywisenbpdcl/',views.dashboardagencywisenbpdcl,name='dashboardagencywisenbpdcl'),
    path('dashboardagencywisesbpdcl/',views.dashboardagencywisesbpdcl,name='dashboardagencywisesbpdcl'),
    path('comparision_dashboard/',views.comparision_dashboard,name='comparision_dashboard'),
    path('comparision_dashboard_sbpdcl/',views.comparision_dashboard_sbpdcl,name='comparision_dashboard_sbpdcl'),
    path('comparision_dashboard_nbpdcl/',views.comparision_dashboard_nbpdcl,name='comparision_dashboard_nbpdcl'),
    path('cons_ac_no_search/',views.cons_wise_details_with_search,name='PersonView'),
    path('cons_passed/',views.cons_passed,name='PersonView'),
    
    path('locationwisehyperlink/',views.locationwisehyperlink,name='PersonView'),
    path('locationwisehyperlinkclick/',views.locationwisehyperlinkclick,name='PersonView'),
    path('meterwisereport/',views.meterWiseReportUpdate,name='PersonView'),
    path('meterwisereportconsumer/',views.meterWiseReportconsumer,name='PersonView'),
    path('spoofimagecheck/',views.spoofimagecheck,name='spoofimagecheck'),
   
    
     # NEW URLS
    path('newmetersummary/',views.new_get_meter_summary,name='PersonView'),
    path('newagencywisesummary/',views.newagencywisesummary,name='PersonView'),
    path('newmvsummary/',views.newmvsummary,name='PersonView'),
    path('newmvsummary/',views.newmvsummary,name='PersonView'),
    path('newmvcheck/',views.newmvcheck,name='PersonView'),
    path('uptime/',views.application_uptime,name='uptime'),
    path('uptimerangenew/',views.application_uptime_range,name='uptimerangenew'),
    path('uptimerange/',views.application_uptime_daily, name = 'uptimeRange'),
    # path('newmvcheck1/',views.newmvcheck1,name='PersonView'),
    path('newlocationwisesummary/',views.new_locationwise_summary,name='PersonView'),
    path('newmeterreaderdetails/',views.meterreaderDetails,name='meterreaderDatails'),
    
    path('newmonthdataa/',views.newmonthdataa,name='PersonView'),
    
    # testAPIS(MATERIALIZEDVIEWS)
    path('minidashboardmonth1/',views.minidashboardmonth1,name='PersonView'),
    path('dashboarddailydata1/',views.dashboarddailydata1,name='PersonView'),
    path('dashboardagencywise1/',views.dashboardagencywise1,name='PersonView'),
    path('exceptionlist1/',views.exceptionlist1,name='PersonView'),
    path('monthwiseexceptiondashboard2/',views.monthwiseexceptiondashboard2,name='PersonView'),
    path('refreshAPI/',views.refreshAPI,name='PersonView'),
    path('discom_mview/',views.discom_summary_mview,name='PersonView'),
    path('zone_mview/',views.zone_summary_mview,name='PersonView'),
    path('circle_mview/',views.circle_summary_mview,name='PersonView'),
    path('division_mview/',views.division_summary_mview,name='PersonView'),
    path('subdivision_mview/',views.subdivision_summary_mview,name='PersonView'),
    path('mrlist_mview/',views.mrlist_mview,name='PersonView'),
    
    
    
    path('newdailydata/',views.newdailydata,name='PersonView'),
    path('newdailybilling/',views.newdailybilling,name='PersonView'),
    
    
    
    path('qccheckmobile/',views.qccheckmobile,name='qccheckmobile'),
    path('qcmobiledashboard/',views.qcmobiledashboard,name='qcmobiledashboard'),
    path('androidclusterstestnew/',views.androidclusterstestnew,name='androidclusterstestnew'),
    path('downloadexcel/',views.downloadexcel,name='downloadexcel'),
    path('mobilemvcards/',views.mobilemvcards,name='mobilemvcards'),
    path('get_officedata/',views.get_officedata,name='get_officedata'),
    path('getofficedata/',views.getofficedata,name='getofficedata'),
    
#    path('failedimages/', views.failedimages, name='failediamges'),
    path('divisiondata/', views.divisiondata, name='divisiondata'),
    path('updatequery/', views.updatequery, name='updatequery'),
    path('updatequery1/', views.updatequery1, name='updatequery1'),
    path('updateddata/', views.updateddata, name='updateddata'),
    # path('mrfailedimages/', views.mr_failed_images, name='mr_failed_images'),
    path('searchbymr/', views.search_by_mr, name='search_by_mr'),
    path('mryes/', views.mrupdatequery, name='mrupdatequery'),
    path('mrno/', views.mrupdatequery1, name='mrupdatequery1'),
    path('mrupdateddata/', views.mrupdateddata, name='mrupdateddata'),
    path('updatespoof/', views.updatespoof, name='updatespoof'),
    path('mrdownloadexcel/', views.mrdownloadexcel, name='mrdownloadexcel'),
    path('downloadexceldata/', views.downloadexceldata, name='downloadexceldata'),
    path('qcdashboard/', views.qcdashboard, name='qcdashboard'),
    path('qcreportdata/', views.qcreportdata, name='qcreportdata'),
    path('qcdailyreport/', views.qcdailyreport, name='qcdailyreport'),
    path('qcmonthlyreport/', views.qcmonthlyreport, name='qcmonthlyreport'),
    path('userdashboard/', views.userdashboard, name='userdashboard'),
    path('mrupdatespoof/', views.mrupdatespoof, name='mrupdatespoof'),
    path('reqcimages/', views.re_qcimages, name='re_qcimages'),
    path('undoimg/', views.undo_img, name='undo_img'),
    path('user_reqc_images/', views.user_reqc_images, name='user_reqc_images'),
    path('recheckdashboard/', views.recheckdashboard, name='recheckdashboard'),
    path('reqc_yes/', views.reqc_yes, name='reqc_yes'),
    path('reqc_no/', views.reqc_no, name='reqc_no'),
    path('reqc_spoof/', views.reqc_spoof, name='reqc_spoof'),

    path('updatemrfault/', views.updatemrfault, name='updatemrfault'),
    path('mrupdatemrfault/', views.mrupdatemrfault, name='mrupdatemrfault'),
    path('reqc_mrfault/', views.reqc_mrfault, name='reqc_mrfault'),

    
    path('originalimageApi/', views.originalimageApi, name='updatequery'),
    path('location_wise_summary_of_agecy/', views.location_wise_summary_of_agecy, name='location_wise_summary_of_agecy'),

    path('meter_reading_summary_new/', views.meter_reading_summary_new, name='meter_reading_summary_new'),
    
    # QC WEB URLS

    path('qcreportdata1/', views.qcreportdata1, name='qcreportdata1'),
    path('qcdailyreport1/', views.qcdailyreport1, name='qcdailyreport1'),
    path('qcmonthlyreport1/', views.qcmonthlyreport1, name='qcmonthlyreport1'),
    path('qcdaywisereport1/', views.qcdaywisereport1, name='qcdaywisereport1'),
    path('getuserdata/', views.getuserdata, name='getuserdata'),
    path('downloadmrlist/', views.downloadmrlist, name='downloadmrlist'),
    path('downloaddivisionlist/', views.downloaddivisionlist,
         name='downloaddivisionlist'),
    path('webqcdashboard/', views.webqcdashboard, name='webqcdashboard'),

    path('reconsilation/', views.reconsilation, name='reconsilation'),
    path('deletereconsilation/', views.deletereconsilation, name='deletereconsiliation'),
    path('uploadxlsx/', views.uploadxlsx, name='uploadxlsx'),
    path('qcStatusChange/', views.process_failed_meter_readings, name='qcstatuschange'),
    path('updateLambdaresults/', views.update_lambda_results_to_db, name= 'updateLambdaresults'),
    path('increaselambdaaccuracy/', views.increase_lambda_accuracy, name= 'increase_lambda_accuracy'),

    
    path('supervisorlogin/', views.supervisorlogin, name='supervisorlogin'),
    path('supervisorlocation/',views.supervisorlocation,name = 'supervisorlocation')

    # path('testdata/',views.testdata,name='PersonView'),
    ]